#!/bin/bash

# ---------------------------
#
# Common settings for all contexts.
#
# ---------------------------
#
# Prefix variables with MLKC_.
#
# ---------------------------
export MLKC_PHD_DATA_VERSION=1.0.0
export MLKC_PHD_DATA_APP=phd_data
export MLKC_PHD_DATA_INSTANCE_GENERATION=$(date +"%Y%m%d-%H%M%S")

# -----
# Common SSH settings
# -----
export MLKC_PHD_DATA_REMOTE_FOLDER=$MLKC_PHD_DATA_SSH_USER_NAME@$MLKC_PHD_DATA_SSH_HOST:/home/apps/phd-data
export MLKC_PHD_DATA_SSH_PORT=22

# -----
# Docker
# -----
export MLKC_PHD_DATA_PRODUCTION_IMAGE=registry.gitlab.com/malkab-phd-data/malkab-phd-data-main_cell_db

# -----
# PostGIS
# -----
export MLKC_PHD_DATA_PG_EXTERNAL_PORT=5532
export MLKC_PHD_DATA_POSTGIS_PASSWORD=postgres

# PG Config for 64GB RAM, 8 CPU, SSD
# This is for PG configuration file, not for the pool
export MLKC_PHD_DATA_PG_MAX_CONNECTIONS=500
export MLKC_PHD_DATA_PG_SHARED_BUFFERS=40GB
export MLKC_PHD_DATA_PG_EFFECTIVE_CACHE_SIZE=122GB
export MLKC_PHD_DATA_PG_MAINTENANCE_WORK_MEM=2GB
export MLKC_PHD_DATA_PG_CHECKPOINT_COMPLETION_TARGET=0.7
export MLKC_PHD_DATA_PG_WAL_BUFFERS=16MB
export MLKC_PHD_DATA_PG_DEFAULT_STATISTICS_TARGET=500
export MLKC_PHD_DATA_PG_RANDOM_PAGE_COST=1.1
export MLKC_PHD_DATA_PG_EFFECTIVE_IO_CONCURRENCY=200
export MLKC_PHD_DATA_PG_WORK_MEM=332MB
export MLKC_PHD_DATA_PG_MIN_WAL_SIZE=512MB
export MLKC_PHD_DATA_PG_MAX_WAL_SIZE=2GB
export MLKC_PHD_DATA_PG_MAX_WORKER_PROCESSES=8
export MLKC_PHD_DATA_PG_MAX_PARALLEL_WORKERS_PER_GATHER=4
export MLKC_PHD_DATA_PG_MAX_PARALLEL_WORKERS=8
export MLKC_PHD_DATA_PG_MAX_PARALLEL_MAINTENANCE_WORKERS=4
