#!/bin/bash

# ---------------------------
#
# Common settings for all contexts, base for development.
#
# ---------------------------
#
# Prefix variables with MLKC_CELL_RAW_DATA_.
#
# ---------------------------
export MLKC_CELL_RAW_DATA_INSTANCE_NAME=dev
export MLKC_CELL_RAW_DATA_VERSION=1.0.0
export MLKC_CELL_RAW_DATA_INSTANCE_GENERATION=$(date +"%Y%m%d-%H%M%S")

# -----
# PostGIS Docker image tag to use
# -----
export MLKC_CELL_RAW_DATA_DOCKER_IMAGE_TAG=holistic_hornet

# -----
# PostGIS for local deployment of both dev and SWARM
# -----
export MLKC_CELL_RAW_DATA_PG_HOST=cell_raw_data_postgis
export MLKC_CELL_RAW_DATA_PG_PORT=5432

# User postgres
export MLKC_CELL_RAW_DATA_PG_USER=postgres
export MLKC_CELL_RAW_DATA_PG_PASS=postgres

# User cell_master
export MLKC_CELL_RAW_DATA_PG_CELL_MASTER_USER=cell_master
export MLKC_CELL_RAW_DATA_PG_CELL_MASTER_PASS=cell_master

# User cell_readonly
export MLKC_CELL_RAW_DATA_PG_CELL_READONLY_USER=cell_readonly
export MLKC_CELL_RAW_DATA_PG_CELL_READONLY_PASS=cell_readonly

# User nacional for the proyecto_nacional DB
export MLKC_CELL_RAW_DATA_PG_NACIONAL_PASS=nacional

# -----
# PG Config for 64GB RAM, 8 CPU, SSD
# This is for PG configuration file, not for the pool
# -----
export MLKC_CELL_RAW_DATA_PG_MAX_CONNECTIONS=200
export MLKC_CELL_RAW_DATA_PG_SHARED_BUFFERS=40GB
export MLKC_CELL_RAW_DATA_PG_EFFECTIVE_CACHE_SIZE=122GB
export MLKC_CELL_RAW_DATA_PG_MAINTENANCE_WORK_MEM=2GB
export MLKC_CELL_RAW_DATA_PG_CHECKPOINT_COMPLETION_TARGET=0.7
export MLKC_CELL_RAW_DATA_PG_WAL_BUFFERS=16MB
export MLKC_CELL_RAW_DATA_PG_DEFAULT_STATISTICS_TARGET=500
export MLKC_CELL_RAW_DATA_PG_RANDOM_PAGE_COST=1.1
export MLKC_CELL_RAW_DATA_PG_EFFECTIVE_IO_CONCURRENCY=200
export MLKC_CELL_RAW_DATA_PG_WORK_MEM=332MB
export MLKC_CELL_RAW_DATA_PG_MIN_WAL_SIZE=512MB
export MLKC_CELL_RAW_DATA_PG_MAX_WAL_SIZE=2GB
export MLKC_CELL_RAW_DATA_PG_MAX_WORKER_PROCESSES=8
export MLKC_CELL_RAW_DATA_PG_MAX_PARALLEL_WORKERS_PER_GATHER=4
export MLKC_CELL_RAW_DATA_PG_MAX_PARALLEL_WORKERS=8
export MLKC_CELL_RAW_DATA_PG_MAX_PARALLEL_MAINTENANCE_WORKERS=4
