#!/bin/bash

# ---------------------------
#
# Common settings for all contexts, base for development.
#
# ---------------------------
#
# Prefix variables with MLKC_CELL_RAW_DATA_.
#
# ---------------------------
export MLKC_CELL_RAW_DATA_INSTANCE_NAME=kerdes

# -----
# SSH access
# -----
export MLKC_CELL_RAW_DATA_SSH_HOST=$MLKC_SYSTEM_KERDES_HOST
export MLKC_CELL_RAW_DATA_SSH_USER=$MLKC_SYSTEM_KERDES_USER
export MLKC_CELL_RAW_DATA_REMOTE_FOLDER=$MLKC_SYSTEM_KERDES_USER@$MLKC_SYSTEM_KERDES_HOST:/home/jpperez/big/cell_raw_data

# -----
# Docker Network
# -----
export MLKC_CELL_RAW_DATA_NETWORK=container:9aacdd28f441

# -----
# PostGIS for local deployment
# -----
export MLKC_CELL_RAW_DATA_PG_HOST=localhost
export MLKC_CELL_RAW_DATA_PG_PORT=5432

# User postgres
export MLKC_CELL_RAW_DATA_PG_USER=$MLKC_SYSTEM_KERDES_PG_USER
export MLKC_CELL_RAW_DATA_PG_PASS=$MLKC_SYSTEM_KERDES_PG_PASS

# User A (me)
export MLKC_CELL_RAW_DATA_PG_USER_ME=$MLKC_SYSTEM_KERDES_USERA
export MLKC_CELL_RAW_DATA_PG_PASS_ME=$MLKC_SYSTEM_KERDES_USERA_PASS

# User cell_master
export MLKC_CELL_RAW_DATA_PG_CELL_MASTER_PASS=$MLKC_SYSTEM_KEPLER_PG_PASS_CELL_MASTER

# User cell_readonly
export MLKC_CELL_RAW_DATA_PG_CELL_READONLY_PASS=$MLKC_SYSTEM_KEPLER_PG_PASS_CELL_READONLY

# User nacional for the proyecto_nacional DB
export MLKC_CELL_RAW_DATA_PG_NACIONAL_PASS=$MLKC_SYSTEM_KEPLER_PG_PASS_NACIONAL
