version: '3.5'

networks:
  cell:
    external: false
    name: ${MLKC_CELL_RAW_DATA_NETWORK}

services:
  cell_raw_data:
    image: malkab/postgis:gargantuan_giraffe
    container_name: cell-${MLKC_CELL_RAW_DATA_APP}_postgis_dev

    environment:
      - PASSWORD=${MLKC_CELL_RAW_DATA_POSTGIS_PASSWORD}

    networks:
      - cell

    ports:
      - "${MLKC_CELL_RAW_DATA_PG_EXTERNAL_PORT}:5432"

    volumes:
      - ../../docker_persistent_volumes/postgis:/data
      - ./config/postgis/postgresql.conf:/default_confs/postgresql.conf
